import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "first_string": "Sign In",
      "second_string": "Email/Username",
      "third string": "Enter your Email",
      "four_string": "Password",
      "fifth_string": "Enter Your Password",
      "sixth_string": "Forget Password",
      "seventh_string": "Remember me",
      "eighth_string": "LOGIN",
      "ninth_string": "Don't have an Accoount",
      "tenth_string": "Sign Up",
      "eleventh_string": "Incident Types",
      "twelve_string": "Emergency Form",
      "thirteenth_string": "First Name",
      "fourteenth_string": "First Name of the Patient",
      "fifteenth_string": "Last Name",
      "sixteenth_string": "Last Name of the Patient",
      "seventeenth_string": "Incident Type",
      "eighteenth_string": "Select type of incident",
      "nineteenth_string": "Bleeding",
      "twenty_string": "Breathing Difficulties",
      "twenty_two_string": "epileptic_seizure",
      "twenty_three_string": "Severe Pain",
      "twenty_four_string": "Heart Attack",
      "twenty_five_string": "A Stroke",
      "twenty_six_string": "Pregnant Woman",
      "twenty_seven_string": "Accident",
      "twenty_eight_string": "Address",
      "twenty_nine_string": "Address of the Incident",
      "thirty_string": "Request"
    },
    'am_ET': {
      "first_string": "ይግቡ",
      "second_string": "ኢሜል/የተጠቃሚ ስም",
      "third string": "ኢሜል/የተጠቃሚ ስም አስገባ",
      "four_string": "የይለፍ ቃል",
      "fifth_string": "የይለፍ ቃል አስገባ",
      "sixth_string": "የይለፍ ቃል ረሳሁ",
      "seventh_string": "አስታወስከኝ",
      "eighth_string": "ግባ",
      "ninth_string": "መለያ የለኝም",
      "tenth_string": "ክፈት",
      "eleventh_string": "የአደጋ ቅጽ",
      "twelve_string": "የድንገተኛ ጊዜ ቅጽ",
      "thirteenth_string": "የመጀመሪያ ስም",
      "fourteenth_string": "የታካሚው የመጀመሪያ ስም",
      "fifteenth_string": "ያባት ስም",
      "sixteenth_string": "የታካሚው የመጨረሻ ስም",
      "seventeenth_string": "የአደጋ አይነት",
      "eighteenth_string": "የአደጋ አይነት ይምረጡ",
      "nineteenth_string": "የደም መፍሰስ",
      "twenty_string": "የመተንፈስ ችግር",
      "twenty_two_string": "የሚጥል በሽታ መናድ",
      "twenty_three_string": "ከባድ ህመም",
      "twenty_four_string": "የልብ ድካም",
      "twenty_five_string": "ስትሮክ",
      "twenty_six_string": "ነፍሰ ጡር ሴት",
      "twenty_seven_string": "የ መኪና አደጋ",
      "twenty_eight_string": "አድራሻ",
      "twenty_nine_string": "የአደጋው አድራሻ",
      "thirty_string": "አምቡላንስ ይጠይቁ"
    }
  };
}